### ISSUE TITLE
Plugin build for Jellyfin 10.6.4

### ISSUE THREAD

**Issue by HTYISABUG** [jellyfin/jellyfin-plugin-anidb#7]
I already tried modified `build.yml`, then build the plugin.
But obviously it doesn't work.

Could you provide plugin build for Jellyfin 10.6.4 ?
Or how can I build it myself?

**Comment by dkanada** [comment]
We won't be releasing official builds for 10.6.4 because there are probably code changes required, as you've discovered here.

**Comment by oddstr13** [comment]
You want the Anime plugin for 10.6, as that plugin was split into this plugin and 3 others for 10.7
If there are any bugs that are fixed here but not in the old plugin, you can apply the fixes yourself and compile that.
https://github.com/jellyfin-archive/jellyfin-plugin-anime
Remember to update the `Jellyfin.Controller` dependency version to target `10.6.*` rather than `10.*-*`

---

`build.yaml` is used by [jprm](https://github.com/oddstr13/jellyfin-plugin-repository-manager), so if you don't use that, changes in `build.yaml` won't have any effect. `targetAbi` is further also *only* used as metadata to determine if a plugin in the repos is (likely) too new to install on the server version you're running.

If you want to build against 10.6, you'll have to change the `Version` field here to `10.6.*`
https://github.com/jellyfin/jellyfin-plugin-anidb/blob/96d74651fb4e43b748cadcc2b9a614123945da6c/Jellyfin.Plugin.AniDB/Jellyfin.Plugin.AniDB.csproj#L11

You may also have to downgrade target framework to `netstandard2.1`, but I'm not sure. If you do have to change that, there's even more that would need changing before you get it compiling again. Try without changing this first, there's plenty that needs changing back for it to compile against 10.6 again.
https://github.com/jellyfin/jellyfin-plugin-anidb/blob/96d74651fb4e43b748cadcc2b9a614123945da6c/Jellyfin.Plugin.AniDB/Jellyfin.Plugin.AniDB.csproj#L4
